mytest/Controllers/BookCommentsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using mytest.Data;
using mytest.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace mytest.Controllers
{
    public class BookCommentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BookCommentsController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: BookComments
        public async Task<IActionResult> Index()
        {
            return View(await _context.Comments.ToListAsync());
        }

        // GET: BookComments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookComment = await _context.Comments
                .SingleOrDefaultAsync(m => m.CommentId == id);
            if (bookComment == null)
            {
                return NotFound();
            }

            return View(bookComment);
        }

        // GET: BookComments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: BookComments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CommentId,Comments,ThisDateTime,BookISBN,Rating")] BookComment bookComment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bookComment);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(bookComment);
        }

        // GET: BookComments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookComment = await _context.Comments.SingleOrDefaultAsync(m => m.CommentId == id);
            if (bookComment == null)
            {
                return NotFound();
            }
            return View(bookComment);
        }

        // POST: BookComments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("CommentId,Comments,ThisDateTime,BookISBN,Rating")] BookComment bookComment)
        {
            if (id != bookComment.CommentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bookComment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookCommentExists(bookComment.CommentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(bookComment);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Add(IFormCollection form)
        {
            var comment = form["Comment"].ToString();
            var bookISBN = form["bookISBN"].ToString();
            var rating = int.Parse(form["Rating"]);
            string userId;
            if (form["Anonymous"].ToString() == "Checked")
                userId = null;
            else
                userId = form["UserId"].ToString();

            BookComment artComment = new BookComment()
            {
                BookISBN = bookISBN,
                Comments = comment,
                Rating = rating,
                ThisDateTime = DateTime.Now,
                UserId = userId
            };

            var ratings = _context.Comments.Where(d => d.BookISBN.Equals(bookISBN)).ToList();
            int ratingSum;
            int ratingCount;
            ratingSum = ratings.Sum(d => d.Rating.Value) + rating;
            ratingCount = ratings.Count()+1;

            var book = _context.Books.Where(x => x.ISBN.Equals(bookISBN)).FirstOrDefault<Book>();
            book.Rating = ratingSum/ratingCount;


            _context.Entry(book).State = EntityState.Modified;
            _context.SaveChanges();

            _context.Comments.Add(artComment);
            _context.SaveChanges();

            return RedirectToAction("ShowBook", "Home", new { field = bookISBN.ToString() });
        }
        // GET: BookComments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookComment = await _context.Comments
                .SingleOrDefaultAsync(m => m.CommentId == id);
            if (bookComment == null)
            {
                return NotFound();
            }

            return View(bookComment);
        }

        // POST: BookComments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bookComment = await _context.Comments.SingleOrDefaultAsync(m => m.CommentId == id);
            var bookISBN = bookComment.BookISBN;
            int rating = (int) bookComment.Rating;
            _context.Comments.Remove(bookComment);
            await _context.SaveChangesAsync();


            var ratings = _context.Comments.Where(d => d.BookISBN.Equals(bookISBN)).ToList();
            int ratingSum = ratings.Sum(d => d.Rating.Value);
            int ratingCount = ratings.Count();
            if (ratingCount != 0)
            {
                var book = _context.Books.Where(x => x.ISBN.Equals(bookISBN)).FirstOrDefault<Book>();
                book.Rating = ratingSum / ratingCount;
                _context.Entry(book).State = EntityState.Modified;
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        private bool BookCommentExists(int id)
        {
            return _context.Comments.Any(e => e.CommentId == id);
        }
    }
}

mytest/Controllers/ShoppingCartsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using mytest.Data;
using mytest.Models;
using System.Linq;
using System.Threading.Tasks;

namespace mytest.Controllers
{
    public class ShoppingCartsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ShoppingCartsController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: ShoppingCarts
        public async Task<IActionResult> Index()
        {
            return View(await _context.MyShoppingCart.ToListAsync());
        }


        // GET: ShoppingCarts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shoppingCart = await _context.MyShoppingCart
                .SingleOrDefaultAsync(m => m.ShoppingCartId == id);
            if (shoppingCart == null)
            {
                return NotFound();
            }

            return View(shoppingCart);
        }

        // GET: ShoppingCarts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ShoppingCarts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ShoppingCartId,UserId,BookISBN,Quantity,Total")] ShoppingCart shoppingCart)
        {
            if (ModelState.IsValid)
            {
                _context.Add(shoppingCart);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(shoppingCart);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Add(IFormCollection form)
        {
            var userId = form["UserId"].ToString();
            var bookISBN = form["BookISBN"].ToString();
            var quantity = int.Parse(form["Quantity"]);
            var book = _context.Books.Where(x => x.ISBN.Equals(bookISBN)).FirstOrDefault<Book>();
            var cartItems = _context.MyShoppingCart.ToList();
            

            foreach (ShoppingCart s in cartItems)
            {
                if (s.BookISBN.Equals(bookISBN) && s.UserId.Equals(userId))
                {
                    s.Quantity += quantity;
                    s.Total = s.Quantity * book.Price;
                    _context.Entry(s).State = EntityState.Modified;
                    _context.SaveChanges();
                    return RedirectToAction("ShowBook", "Home", new { field = bookISBN.ToString() });
                }
            }
            ShoppingCart item = new ShoppingCart()
            {
                UserId = userId,
                BookISBN = bookISBN,
                Quantity = quantity,
                Total = quantity * book.Price
            };


            _context.MyShoppingCart.Add(item);
            _context.SaveChanges();

            return RedirectToAction("ShowBook", "Home", new { field = bookISBN.ToString() });
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult UpdateQuantity(IFormCollection form)
        {
            var userId = form["UserId"].ToString();
            var bookISBN = form["BookISBN"].ToString();
            var quantity = int.Parse(form["Quantity"]);
            var book = _context.Books.Where(x => x.ISBN.Equals(bookISBN)).FirstOrDefault<Book>();
            var cartItems = _context.MyShoppingCart.ToList();
            bool check = false;
            if (form["toCheckOut"].ToString() == "Checked")
                check = true;
            foreach (ShoppingCart s in cartItems)
            {
                if (s.BookISBN.Equals(bookISBN) && s.UserId.Equals(userId))
                {
                    s.Quantity = quantity;
                    s.Total = s.Quantity * book.Price;
                    s.Checked = check;
                    _context.Entry(s).State = EntityState.Modified;
                    _context.SaveChanges();
                    return RedirectToAction("ShoppingCart", "Home");
                }
            }

            return RedirectToAction("ShoppingCart", "Home");
        }



        // GET: ShoppingCarts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shoppingCart = await _context.MyShoppingCart.SingleOrDefaultAsync(m => m.ShoppingCartId == id);
            if (shoppingCart == null)
            {
                return NotFound();
            }
            return View(shoppingCart);
        }

        // POST: ShoppingCarts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ShoppingCartId,UserId,BookISBN,Quantity,Total")] ShoppingCart shoppingCart)
        {
            if (id != shoppingCart.ShoppingCartId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(shoppingCart);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShoppingCartExists(shoppingCart.ShoppingCartId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(shoppingCart);
        }

        // GET: ShoppingCarts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shoppingCart = await _context.MyShoppingCart
                .SingleOrDefaultAsync(m => m.ShoppingCartId == id);
            if (shoppingCart == null)
            {
                return NotFound();
            }

            return View(shoppingCart);
        }

        // POST: ShoppingCarts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var shoppingCart = await _context.MyShoppingCart.SingleOrDefaultAsync(m => m.ShoppingCartId == id);
            _context.MyShoppingCart.Remove(shoppingCart);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool ShoppingCartExists(int id)
        {
            return _context.MyShoppingCart.Any(e => e.ShoppingCartId == id);
        }
    }
}

mytest/Views/Shared/AddToCart.cshtml
@{
    ViewData["Title"] = "AddToCart";
    var list = new List<SelectListItem>();
    ViewBag.Quantity++;
    @for(var i = 1; i < ViewBag.Quantity; i++)
    {
        list.Add(new SelectListItem { Text = i.ToString(), Value = i.ToString() });

    }
    ViewBag.list = list;

}

@using (Html.BeginForm("Add", "ShoppingCarts", FormMethod.Post))
            {
    @Html.AntiForgeryToken()
        <a class="form-group">
                <input type="hidden" name="BookISBN" value="@ViewBag.BookISBN" />
                <input type="hidden" name="UserId" id="UserId" value="@ViewBag.UserId" />
                @*<input name="Quantity"  id="Quantity" class="dropdown" value=Quantity />*@
                Qty
                @Html.DropDownList("Quantity", new SelectList(ViewBag.list, "Text", "Value"))<input type="submit" id="btnRegister" name="btnRegister" value="Add To Cart" class="btn btn-primary" role="button" style="margin-left:30px" />
                
        </a>

}

mytest/Views/Shared/CardInfo.cshtml
@model IEnumerable<mytest.Models.ShoppingCart>
@{
    ViewData["Title"] = "CardInfo";
    var userItems = ViewBag.userItems;
    var booksInCart = ViewBag.booksInCart;
    Book mybook = new Book();
    double total = 0.00;
    var user = ViewBag.user;
    var UserId = ViewBag.UserId;
    var date = ViewBag.date;

}

@using (Html.BeginForm("AfterPurchase", "Home", FormMethod.Post))
{

<div class="container">
        <div class="col-lg-6">
            <legend>Card Details</legend>
            <div>
                    <div class="card">
                        <div class="front side">
                            <span class="company">
                                CARD
                            </span>
                            PAYMENT CARD
                            <input type="text" id="CCnum" required value="@user.CCnum" class="cc-num" maxlength="16" min="999999999999999" />
                            <div>
                                Expires:
                                <input id="month" type="month" name="month"
                                       min=@date required>
                                <span class="validity"></span>/>
                            </div>
                            <div>
                                CVC:
                                <input type="text" id="CVC"  placeholder="000" class="cc-cvc" maxlength="3" />
                            </div>
                        </div>
                        </div>
            </div>
        </div>
    <div class="col-lg-6">
        <!-- Form Name -->
        <legend>Address Details</legend>
        <!-- Text input-->
        <div class="form-group">
            <label class="col-sm-2 control-label" for="textinput">Address</label>
            <div class="col-sm-10">
                <input type="text" placeholder="Address" class="form-control"><br>
            </div>
        </div>
        <!-- Text input-->
        <div class="form-group">
            <label class="col-sm-2 control-label" for="textinput">City</label>
            <div class="col-sm-10">
                <input type="text" placeholder="City" class="form-control"><br>
            </div>
        </div>
        <!-- Text input-->
        <div class="form-group">
            <label class="col-sm-2 control-label" for="textinput">State</label>
            <div class="col-sm-10">
                <input type="text" placeholder="State" class="form-control"><br>
            </div>

        </div>
        <!-- Text input-->
        <div class="form-group">
            <label class="col-sm-2 control-label" for="textinput">Country</label>
            <div class="col-sm-10">
                <input type="text" placeholder="Country" class="form-control"><br>
            </div>
        </div>
        </div>
</div>


<legend>Items</legend>
<div class="container">
    <div class="col-lg-12">
        <table id="cart" class="table table-condensed">
            <thead>
                <tr>
                    <th style="width:60%">Books</th>
                    <th style="width:5%">Price</th>
                    <th style="width:20%">Qty</th>
                    <th style="width:20%">Subtotal</th>
                </tr>
            </thead>
            @foreach (var item in @userItems)
            {
                if (item.Checked == true)
                {
                    total += item.Total;
                    foreach (Book b in booksInCart)
                    {
                        if (b.ISBN.Equals(@item.BookISBN))
                        {
                            mybook = b;
                        }
                    }

                <tbody>
                    <tr>
                        @using (Html.BeginForm("UpdateQuantity", "ShoppingCarts", FormMethod.Post))
                        {
                            <td data-th="Product">@mybook.Title</td>
                            <td data-th="Price">$@mybook.Price</td>
                            <td data-th="Quantity">@(@item.Quantity)</td>
                            <td data-th="Subtotal">$@(@mybook.Price * @item.Quantity)</td>

                        }
                    </tr>
                </tbody>
                }

            }
        </table>
        <table id="cart" class="table table-hover table-condensed">
            <tr>
                <td class="hidden-xs text-right"><strong class="fa fa-angle-right">Total $@total    </strong></td>
            </tr>
        </table>
    </div>
</div>


<div class="col-lg-12" style="text-align:center">
            <a href="~/Home/Index" class="btn btn-warning"><i class="fa fa-angle-left"></i> Continue Shopping</a>
            <input type="hidden" name="userItems" id="userItems" value=@userItems />
            <input type="hidden" name="booksInCart" id="booksInCart" value=@booksInCart />
            <input type="hidden" name="UserId" id="UserId" value="@UserId" />
            <input type="submit" id="btnRegister" name="btnRegister" value="Buy" class="btn btn-success">

</div>

}

mytest/Views/Shared/CommentBox.cshtml
<dl class="dl-horizontal">


        <div class="commentBox">
            @using (Html.BeginForm("Add", "BookComments", FormMethod.Post, new { onsubmit = "return SubmitComment()" }))
            {
                @Html.AntiForgeryToken()
                <div class="form-horizontal">
                    <div class="form-group">
                        <label class="col-md-4 control-label">
                            Your rating <span style="font-weight:normal;">(1 star is bad, 5 stars is good)</span>
                        </label>
                        <div class="col-md-7">
                            <div onmouseout="CRateSelected()">
                                <span class="starFade" id="Rate1" onclick="CRate(1)" onmouseover="CRateOver(1)" onmouseout="CRateOut(1)" style="min-width: 30px; min-height: 30px"></span><span class="starFade" id="Rate2" onclick="CRate(2)" onmouseover="CRateOver(2)" onmouseout="CRateOut(2)" style="min-width: 30px; min-height: 30px"></span><span class="starFade" id="Rate3" onclick="CRate(3)" onmouseover="CRateOver(3)" onmouseout="CRateOut(3)" style="min-width: 30px; min-height: 30px"></span><span class="starFade" id="Rate4" onclick="CRate(4)" onmouseover="CRateOver(4)" onmouseout="CRateOut(4)" style="min-width: 30px; min-height: 30px"></span><span class="starFade" id="Rate5" onclick="CRate(5)" onmouseover="CRateOver(5)" onmouseout="CRateOut(5)" style="min-width: 30px; min-height: 30px"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <textarea name="Comment" id="Comment" maxlength="900" required rows="5" style="width:940px; margin-left:50px" class="form-control" placeholder = "Comment your experience (900 characters max)"></textarea>
                        </div>
                    </div>
                    
                    
                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="checkbox" name="Anonymous" value="Checked" style="margin-left:50px"> Comment as Anonymous<br>
                            <input type="hidden" name="BookISBN" value="@ViewBag.BookISBN" />
                            <input type="hidden" name="Rating" id="Rating" value="0" />
                            <input type="hidden" name="UserId" id="UserId" value="@ViewBag.UserName" />
                            <br />
                            <input type="submit" id="btnRegister" name="btnRegister" value="Submit Comment" class="btn btn-warning" style="margin-left:50px"/>
                        </div>
                    </div>

                </div>
            }

        </div>

</dl>
<script>
        function SubmitComment() {
            if ($("#Rating").val() == "0") {
                alert("Please rate this book.");
                return false;
            }
            else {
                return true;
            }
        }

        function CRate(r) {
            $("#Rating").val(r);
            for (var i = 1; i <= r; i++) {
                $("#Rate" + i).attr('class', 'starGlow');
            }
            // unselect remaining
            for (var i = r + 1; i <= 5; i++) {
                $("#Rate" + i).attr('class', 'starFade');
            }
        }

        function CRateOver(r) {
            for (var i = 1; i <= r; i++) {
                $("#Rate" + i).attr('class', 'starGlow');
            }
        }

        function CRateOut(r) {
            for (var i = 1; i <= r; i++) {
                $("#Rate" + i).attr('class', 'starFade');
            }
        }

        function CRateSelected() {
            var setRating = $("#Rating").val();
            for (var i = 1; i <= setRating; i++) {
                $("#Rate" + i).attr('class', 'starGlow');
            }
        }
</script>

mytest/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mytest</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/hover.css" />
        <link rel="stylesheet" href="~/css/hover-min.css" />
        <link rel="stylesheet" href="~/css/tab.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">GeekText</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Team 5</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="https://stripe.github.io/jquery.payment/lib/jquery.payment.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        <script src="//production-assets.codepen.io/assets/common/stopExecutionOnTimeout-b2a7b3f….js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>